ccflags-y += -Idrivers/media/platform/msm/camera_lenovo/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_lenovo/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/camera_lenovo/cam_sensor_module/cam_sensor_io
ccflags-y += -Idrivers/media/platform/msm/camera_lenovo/cam_sensor_module/cam_sensor_utils
ccflags-y += -Idrivers/media/platform/msm/camera_lenovo/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_lenovo/cam_smmu/

obj-$(CONFIG_SPECTRA_CAMERA) += cam_cci_dev.o cam_cci_core.o cam_cci_soc.o
