ccflags-y += -Idrivers/media/platform/msm/camera_lenovo/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_lenovo/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_lenovo/cam_sensor_module/cam_sensor_io
ccflags-y += -Idrivers/media/platform/msm/camera_lenovo/cam_sensor_module/cam_cci
ccflags-y += -Idrivers/media/platform/msm/camera_lenovo/cam_sensor_module/cam_res_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_lenovo/cam_smmu/
ccflags-y += -Idrivers/media/platform/msm/camera_lenovo/cam_cpas/include

obj-$(CONFIG_SPECTRA_CAMERA) +=  cam_sensor_util.o
