ccflags-y += -Idrivers/media/platform/msm/camera_lenovo/cam_core/
ccflags-y += -Idrivers/media/platform/msm/camera_lenovo/cam_req_mgr/
ccflags-y += -Idrivers/media/platform/msm/camera_lenovo/cam_smmu/

obj-$(CONFIG_SPECTRA_CAMERA) += cam_soc_util.o cam_io_util.o cam_packet_util.o cam_debug_util.o cam_trace.o cam_common_util.o
